{
 "title": "Crypto Tests",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Key Generation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "SELECT \n    datetime,\n    AVG(CASE WHEN algorithm_name LIKE 'Dilithium%' THEN duration ELSE NULL END) AS Dilithium,\n    AVG(CASE WHEN algorithm_name = 'ECDSA' THEN duration ELSE NULL END) AS ECDSA,\n    AVG(CASE WHEN algorithm_name LIKE 'Falcon%' THEN duration ELSE NULL END) AS Falcon,\n    AVG(CASE WHEN algorithm_name LIKE 'SPHINCS+%' THEN duration ELSE NULL END) AS Sphincs\nFROM crypto_tests_data\nWHERE test_name = 'GenerateKey'\nGROUP BY datetime",
     "rawQueryText": "SELECT \n    datetime,\n    AVG(CASE WHEN algorithm_name LIKE 'Dilithium%' THEN duration ELSE NULL END) AS Dilithium,\n    AVG(CASE WHEN algorithm_name = 'ECDSA' THEN duration ELSE NULL END) AS ECDSA,\n    AVG(CASE WHEN algorithm_name LIKE 'Falcon%' THEN duration ELSE NULL END) AS Falcon,\n    AVG(CASE WHEN algorithm_name LIKE 'SPHINCS+%' THEN duration ELSE NULL END) AS Sphincs\nFROM crypto_tests_data\nWHERE test_name = 'GenerateKey'\nGROUP BY datetime"
    }
   ]
  },
  {
   "title": "Signature Generation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "SELECT \n    datetime,\n    AVG(CASE WHEN algorithm_name LIKE 'Dilithium%' THEN duration ELSE NULL END) AS Dilithium,\n    AVG(CASE WHEN algorithm_name = 'ECDSA' THEN duration ELSE NULL END) AS ECDSA,\n    AVG(CASE WHEN algorithm_name LIKE 'Falcon%' THEN duration ELSE NULL END) AS Falcon,\n    AVG(CASE WHEN algorithm_name LIKE 'SPHINCS+%' THEN duration ELSE NULL END) AS Sphincs\nFROM crypto_tests_data\nWHERE test_name = 'GenerateSignature'\nGROUP BY datetime",
     "rawQueryText": "SELECT \n    datetime,\n    AVG(CASE WHEN algorithm_name LIKE 'Dilithium%' THEN duration ELSE NULL END) AS Dilithium,\n    AVG(CASE WHEN algorithm_name = 'ECDSA' THEN duration ELSE NULL END) AS ECDSA,\n    AVG(CASE WHEN algorithm_name LIKE 'Falcon%' THEN duration ELSE NULL END) AS Falcon,\n    AVG(CASE WHEN algorithm_name LIKE 'SPHINCS+%' THEN duration ELSE NULL END) AS Sphincs\nFROM crypto_tests_data\nWHERE test_name = 'GenerateSignature'\nGROUP BY datetime"
    }
   ]
  },
  {
   "title": "Signature Verification",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "SELECT \n    datetime,\n    AVG(CASE WHEN algorithm_name LIKE 'Dilithium%' THEN duration ELSE NULL END) AS Dilithium,\n    AVG(CASE WHEN algorithm_name = 'ECDSA' THEN duration ELSE NULL END) AS ECDSA,\n    AVG(CASE WHEN algorithm_name LIKE 'Falcon%' THEN duration ELSE NULL END) AS Falcon,\n    AVG(CASE WHEN algorithm_name LIKE 'SPHINCS+%' THEN duration ELSE NULL END) AS Sphincs\nFROM crypto_tests_data\nWHERE test_name = 'VerifySignature'\nGROUP BY datetime",
     "rawQueryText": "SELECT \n    datetime,\n    AVG(CASE WHEN algorithm_name LIKE 'Dilithium%' THEN duration ELSE NULL END) AS Dilithium,\n    AVG(CASE WHEN algorithm_name = 'ECDSA' THEN duration ELSE NULL END) AS ECDSA,\n    AVG(CASE WHEN algorithm_name LIKE 'Falcon%' THEN duration ELSE NULL END) AS Falcon,\n    AVG(CASE WHEN algorithm_name LIKE 'SPHINCS+%' THEN duration ELSE NULL END) AS Sphincs\nFROM crypto_tests_data\nWHERE test_name = 'VerifySignature'\nGROUP BY datetime"
    }
   ]
  }
 ]
}