{
 "title": "📊 Historical data for key generation",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "📊🔑 Key Generation Historical data",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT \n    algorithm_name AS \"Algorithm\",\n    AVG(duration) AS \"Duration (avg.)\",\n    AVG(alloc) AS \"Alloc (avg.)\",\n    AVG(total_alloc) AS \"Total alloc (avg.)\",\n    AVG(sys) AS \"Sys (avg.)\",\n    AVG(num_gc) AS \"Num GC (avg.)\"\nFROM crypto_tests_data\nWHERE test_name = 'GenerateKey'\nGROUP BY algorithm_name;\n",
     "rawQueryText": "SELECT \n    algorithm_name AS \"Algorithm\",\n    AVG(duration) AS \"Duration (avg.)\",\n    AVG(alloc) AS \"Alloc (avg.)\",\n    AVG(total_alloc) AS \"Total alloc (avg.)\",\n    AVG(sys) AS \"Sys (avg.)\",\n    AVG(num_gc) AS \"Num GC (avg.)\"\nFROM crypto_tests_data\nWHERE test_name = 'GenerateKey'\nGROUP BY algorithm_name;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "⏱️ Average Execution Time",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "queryText": "SELECT \n    algorithm_name,\n    AVG(duration) AS avg_duration\nFROM crypto_tests_data\nWHERE test_name = 'GenerateKey'\nGROUP BY algorithm_name;\n",
     "rawQueryText": "SELECT \n    algorithm_name,\n    AVG(duration) AS avg_duration\nFROM crypto_tests_data\nWHERE test_name = 'GenerateKey'\nGROUP BY algorithm_name;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "💾 Average Alloc",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "queryText": "SELECT \n    algorithm_name,\n    AVG(alloc) AS avg_alloc\nFROM crypto_tests_data\nWHERE test_name = 'GenerateKey'\nGROUP BY algorithm_name;\n",
     "rawQueryText": "SELECT \n    algorithm_name,\n    AVG(alloc) AS avg_alloc\nFROM crypto_tests_data\nWHERE test_name = 'GenerateKey'\nGROUP BY algorithm_name;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "💾 Average Total Alloc",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 36 },
   "targets": [
    {
     "queryText": "SELECT \n    algorithm_name,\n    AVG(total_alloc) AS avg_total_alloc\nFROM crypto_tests_data\nWHERE test_name = 'GenerateKey'\nGROUP BY algorithm_name;\n",
     "rawQueryText": "SELECT \n    algorithm_name,\n    AVG(total_alloc) AS avg_total_alloc\nFROM crypto_tests_data\nWHERE test_name = 'GenerateKey'\nGROUP BY algorithm_name;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "⚙️ Average Sys",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "queryText": "SELECT \n    algorithm_name,\n    AVG(sys) AS avg_sys\nFROM crypto_tests_data\nWHERE test_name = 'GenerateKey'\nGROUP BY algorithm_name;\n",
     "rawQueryText": "SELECT \n    algorithm_name,\n    AVG(sys) AS avg_sys\nFROM crypto_tests_data\nWHERE test_name = 'GenerateKey'\nGROUP BY algorithm_name;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "🔧 Average Num GC",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 36 },
   "targets": [
    {
     "queryText": "SELECT \n    algorithm_name,\n    AVG(num_gc) AS avg_num_gc\nFROM crypto_tests_data\nWHERE test_name = 'GenerateKey'\nGROUP BY algorithm_name;\n",
     "rawQueryText": "SELECT \n    algorithm_name,\n    AVG(num_gc) AS avg_num_gc\nFROM crypto_tests_data\nWHERE test_name = 'GenerateKey'\nGROUP BY algorithm_name;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}