{
 "title": "Crypto Tests",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "⏱️ Execution Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "🔑 Key Generation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "queryText": "SELECT \n    datetime,\n    AVG(CASE WHEN algorithm_name LIKE 'Dilithium%' THEN duration ELSE NULL END) AS Dilithium,\n    AVG(CASE WHEN algorithm_name = 'ECDSA' THEN duration ELSE NULL END) AS ECDSA,\n    AVG(CASE WHEN algorithm_name LIKE 'Falcon%' THEN duration ELSE NULL END) AS Falcon,\n    AVG(CASE WHEN algorithm_name LIKE 'SPHINCS+%' THEN duration ELSE NULL END) AS Sphincs\nFROM crypto_tests_data\nWHERE test_name = 'GenerateKey'\nGROUP BY datetime",
       "rawQueryText": "SELECT \n    datetime,\n    AVG(CASE WHEN algorithm_name LIKE 'Dilithium%' THEN duration ELSE NULL END) AS Dilithium,\n    AVG(CASE WHEN algorithm_name = 'ECDSA' THEN duration ELSE NULL END) AS ECDSA,\n    AVG(CASE WHEN algorithm_name LIKE 'Falcon%' THEN duration ELSE NULL END) AS Falcon,\n    AVG(CASE WHEN algorithm_name LIKE 'SPHINCS+%' THEN duration ELSE NULL END) AS Sphincs\nFROM crypto_tests_data\nWHERE test_name = 'GenerateKey'\nGROUP BY datetime"
      }
     ]
    },
    {
     "title": "✍ Signature Generation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "queryText": "SELECT \n    datetime,\n    AVG(CASE WHEN algorithm_name LIKE 'Dilithium%' THEN duration ELSE NULL END) AS Dilithium,\n    AVG(CASE WHEN algorithm_name = 'ECDSA' THEN duration ELSE NULL END) AS ECDSA,\n    AVG(CASE WHEN algorithm_name LIKE 'Falcon%' THEN duration ELSE NULL END) AS Falcon,\n    AVG(CASE WHEN algorithm_name LIKE 'SPHINCS+%' THEN duration ELSE NULL END) AS Sphincs\nFROM crypto_tests_data\nWHERE test_name = 'GenerateSignature'\nGROUP BY datetime",
       "rawQueryText": "SELECT \n    datetime,\n    AVG(CASE WHEN algorithm_name LIKE 'Dilithium%' THEN duration ELSE NULL END) AS Dilithium,\n    AVG(CASE WHEN algorithm_name = 'ECDSA' THEN duration ELSE NULL END) AS ECDSA,\n    AVG(CASE WHEN algorithm_name LIKE 'Falcon%' THEN duration ELSE NULL END) AS Falcon,\n    AVG(CASE WHEN algorithm_name LIKE 'SPHINCS+%' THEN duration ELSE NULL END) AS Sphincs\nFROM crypto_tests_data\nWHERE test_name = 'GenerateSignature'\nGROUP BY datetime"
      }
     ]
    },
    {
     "title": "📝 Signature Verification",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "queryText": "SELECT \n    datetime,\n    AVG(CASE WHEN algorithm_name LIKE 'Dilithium%' THEN duration ELSE NULL END) AS Dilithium,\n    AVG(CASE WHEN algorithm_name = 'ECDSA' THEN duration ELSE NULL END) AS ECDSA,\n    AVG(CASE WHEN algorithm_name LIKE 'Falcon%' THEN duration ELSE NULL END) AS Falcon,\n    AVG(CASE WHEN algorithm_name LIKE 'SPHINCS+%' THEN duration ELSE NULL END) AS Sphincs\nFROM crypto_tests_data\nWHERE test_name = 'VerifySignature'\nGROUP BY datetime",
       "rawQueryText": "SELECT \n    datetime,\n    AVG(CASE WHEN algorithm_name LIKE 'Dilithium%' THEN duration ELSE NULL END) AS Dilithium,\n    AVG(CASE WHEN algorithm_name = 'ECDSA' THEN duration ELSE NULL END) AS ECDSA,\n    AVG(CASE WHEN algorithm_name LIKE 'Falcon%' THEN duration ELSE NULL END) AS Falcon,\n    AVG(CASE WHEN algorithm_name LIKE 'SPHINCS+%' THEN duration ELSE NULL END) AS Sphincs\nFROM crypto_tests_data\nWHERE test_name = 'VerifySignature'\nGROUP BY datetime"
      }
     ]
    }
   ]
  },
  {
   "title": "💾 Total Alloc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "🔑 Key Generation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "queryText": "SELECT \n    datetime,\n    AVG(CASE WHEN algorithm_name LIKE 'Dilithium%' THEN alloc ELSE NULL END) AS Dilithium,\n    AVG(CASE WHEN algorithm_name = 'ECDSA' THEN alloc ELSE NULL END) AS ECDSA,\n    AVG(CASE WHEN algorithm_name LIKE 'Falcon%' THEN alloc ELSE NULL END) AS Falcon,\n    AVG(CASE WHEN algorithm_name LIKE 'SPHINCS+%' THEN alloc ELSE NULL END) AS Sphincs\nFROM crypto_tests_data\nWHERE test_name = 'GenerateKey'\nGROUP BY datetime",
       "rawQueryText": "SELECT \n    datetime,\n    AVG(CASE WHEN algorithm_name LIKE 'Dilithium%' THEN alloc ELSE NULL END) AS Dilithium,\n    AVG(CASE WHEN algorithm_name = 'ECDSA' THEN alloc ELSE NULL END) AS ECDSA,\n    AVG(CASE WHEN algorithm_name LIKE 'Falcon%' THEN alloc ELSE NULL END) AS Falcon,\n    AVG(CASE WHEN algorithm_name LIKE 'SPHINCS+%' THEN alloc ELSE NULL END) AS Sphincs\nFROM crypto_tests_data\nWHERE test_name = 'GenerateKey'\nGROUP BY datetime"
      }
     ]
    },
    {
     "title": "✍ Signature Generation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "queryText": "SELECT \n    datetime,\n    AVG(CASE WHEN algorithm_name LIKE 'Dilithium%' THEN alloc ELSE NULL END) AS Dilithium,\n    AVG(CASE WHEN algorithm_name = 'ECDSA' THEN alloc ELSE NULL END) AS ECDSA,\n    AVG(CASE WHEN algorithm_name LIKE 'Falcon%' THEN alloc ELSE NULL END) AS Falcon,\n    AVG(CASE WHEN algorithm_name LIKE 'SPHINCS+%' THEN alloc ELSE NULL END) AS Sphincs\nFROM crypto_tests_data\nWHERE test_name = 'GenerateSignature'\nGROUP BY datetime",
       "rawQueryText": "SELECT \n    datetime,\n    AVG(CASE WHEN algorithm_name LIKE 'Dilithium%' THEN alloc ELSE NULL END) AS Dilithium,\n    AVG(CASE WHEN algorithm_name = 'ECDSA' THEN alloc ELSE NULL END) AS ECDSA,\n    AVG(CASE WHEN algorithm_name LIKE 'Falcon%' THEN alloc ELSE NULL END) AS Falcon,\n    AVG(CASE WHEN algorithm_name LIKE 'SPHINCS+%' THEN alloc ELSE NULL END) AS Sphincs\nFROM crypto_tests_data\nWHERE test_name = 'GenerateSignature'\nGROUP BY datetime"
      }
     ]
    },
    {
     "title": "📝 Signature Verification",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 6, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "queryText": "SELECT \n    datetime,\n    AVG(CASE WHEN algorithm_name LIKE 'Dilithium%' THEN alloc ELSE NULL END) AS Dilithium,\n    AVG(CASE WHEN algorithm_name = 'ECDSA' THEN alloc ELSE NULL END) AS ECDSA,\n    AVG(CASE WHEN algorithm_name LIKE 'Falcon%' THEN alloc ELSE NULL END) AS Falcon,\n    AVG(CASE WHEN algorithm_name LIKE 'SPHINCS+%' THEN alloc ELSE NULL END) AS Sphincs\nFROM crypto_tests_data\nWHERE test_name = 'VerifySignature'\nGROUP BY datetime",
       "rawQueryText": "SELECT \n    datetime,\n    AVG(CASE WHEN algorithm_name LIKE 'Dilithium%' THEN alloc ELSE NULL END) AS Dilithium,\n    AVG(CASE WHEN algorithm_name = 'ECDSA' THEN alloc ELSE NULL END) AS ECDSA,\n    AVG(CASE WHEN algorithm_name LIKE 'Falcon%' THEN alloc ELSE NULL END) AS Falcon,\n    AVG(CASE WHEN algorithm_name LIKE 'SPHINCS+%' THEN alloc ELSE NULL END) AS Sphincs\nFROM crypto_tests_data\nWHERE test_name = 'VerifySignature'\nGROUP BY datetime"
      }
     ]
    }
   ]
  },
  { "title": "⚙️ Sys (Kb)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "🔑 Key Generation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "SELECT \n    datetime,\n    AVG(CASE WHEN algorithm_name LIKE 'Dilithium%' THEN sys ELSE NULL END) AS Dilithium,\n    AVG(CASE WHEN algorithm_name = 'ECDSA' THEN sys ELSE NULL END) AS ECDSA,\n    AVG(CASE WHEN algorithm_name LIKE 'Falcon%' THEN sys ELSE NULL END) AS Falcon,\n    AVG(CASE WHEN algorithm_name LIKE 'SPHINCS+%' THEN sys ELSE NULL END) AS Sphincs\nFROM crypto_tests_data\nWHERE test_name = 'GenerateKey'\nGROUP BY datetime",
     "rawQueryText": "SELECT \n    datetime,\n    AVG(CASE WHEN algorithm_name LIKE 'Dilithium%' THEN sys ELSE NULL END) AS Dilithium,\n    AVG(CASE WHEN algorithm_name = 'ECDSA' THEN sys ELSE NULL END) AS ECDSA,\n    AVG(CASE WHEN algorithm_name LIKE 'Falcon%' THEN sys ELSE NULL END) AS Falcon,\n    AVG(CASE WHEN algorithm_name LIKE 'SPHINCS+%' THEN sys ELSE NULL END) AS Sphincs\nFROM crypto_tests_data\nWHERE test_name = 'GenerateKey'\nGROUP BY datetime"
    }
   ]
  },
  {
   "title": "✍ Signature Generation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "SELECT \n    datetime,\n    AVG(CASE WHEN algorithm_name LIKE 'Dilithium%' THEN sys ELSE NULL END) AS Dilithium,\n    AVG(CASE WHEN algorithm_name = 'ECDSA' THEN sys ELSE NULL END) AS ECDSA,\n    AVG(CASE WHEN algorithm_name LIKE 'Falcon%' THEN sys ELSE NULL END) AS Falcon,\n    AVG(CASE WHEN algorithm_name LIKE 'SPHINCS+%' THEN sys ELSE NULL END) AS Sphincs\nFROM crypto_tests_data\nWHERE test_name = 'GenerateSignature'\nGROUP BY datetime",
     "rawQueryText": "SELECT \n    datetime,\n    AVG(CASE WHEN algorithm_name LIKE 'Dilithium%' THEN sys ELSE NULL END) AS Dilithium,\n    AVG(CASE WHEN algorithm_name = 'ECDSA' THEN sys ELSE NULL END) AS ECDSA,\n    AVG(CASE WHEN algorithm_name LIKE 'Falcon%' THEN sys ELSE NULL END) AS Falcon,\n    AVG(CASE WHEN algorithm_name LIKE 'SPHINCS+%' THEN sys ELSE NULL END) AS Sphincs\nFROM crypto_tests_data\nWHERE test_name = 'GenerateSignature'\nGROUP BY datetime"
    }
   ]
  },
  {
   "title": "📝 Signature Verification",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "SELECT \n    datetime,\n    AVG(CASE WHEN algorithm_name LIKE 'Dilithium%' THEN sys ELSE NULL END) AS Dilithium,\n    AVG(CASE WHEN algorithm_name = 'ECDSA' THEN sys ELSE NULL END) AS ECDSA,\n    AVG(CASE WHEN algorithm_name LIKE 'Falcon%' THEN sys ELSE NULL END) AS Falcon,\n    AVG(CASE WHEN algorithm_name LIKE 'SPHINCS+%' THEN sys ELSE NULL END) AS Sphincs\nFROM crypto_tests_data\nWHERE test_name = 'VerifySignature'\nGROUP BY datetime",
     "rawQueryText": "SELECT \n    datetime,\n    AVG(CASE WHEN algorithm_name LIKE 'Dilithium%' THEN sys ELSE NULL END) AS Dilithium,\n    AVG(CASE WHEN algorithm_name = 'ECDSA' THEN sys ELSE NULL END) AS ECDSA,\n    AVG(CASE WHEN algorithm_name LIKE 'Falcon%' THEN sys ELSE NULL END) AS Falcon,\n    AVG(CASE WHEN algorithm_name LIKE 'SPHINCS+%' THEN sys ELSE NULL END) AS Sphincs\nFROM crypto_tests_data\nWHERE test_name = 'VerifySignature'\nGROUP BY datetime"
    }
   ]
  },
  { "title": "🔧 Num GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "🔑 Key Generation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "SELECT \n    datetime,\n    AVG(CASE WHEN algorithm_name LIKE 'Dilithium%' THEN num_gc ELSE NULL END) AS Dilithium,\n    AVG(CASE WHEN algorithm_name = 'ECDSA' THEN num_gc ELSE NULL END) AS ECDSA,\n    AVG(CASE WHEN algorithm_name LIKE 'Falcon%' THEN num_gc ELSE NULL END) AS Falcon,\n    AVG(CASE WHEN algorithm_name LIKE 'SPHINCS+%' THEN num_gc ELSE NULL END) AS Sphincs\nFROM crypto_tests_data\nWHERE test_name = 'GenerateKey'\nGROUP BY datetime",
     "rawQueryText": "SELECT \n    datetime,\n    AVG(CASE WHEN algorithm_name LIKE 'Dilithium%' THEN num_gc ELSE NULL END) AS Dilithium,\n    AVG(CASE WHEN algorithm_name = 'ECDSA' THEN num_gc ELSE NULL END) AS ECDSA,\n    AVG(CASE WHEN algorithm_name LIKE 'Falcon%' THEN num_gc ELSE NULL END) AS Falcon,\n    AVG(CASE WHEN algorithm_name LIKE 'SPHINCS+%' THEN num_gc ELSE NULL END) AS Sphincs\nFROM crypto_tests_data\nWHERE test_name = 'GenerateKey'\nGROUP BY datetime"
    }
   ]
  },
  {
   "title": "✍ Signature Generation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "SELECT \n    datetime,\n    AVG(CASE WHEN algorithm_name LIKE 'Dilithium%' THEN num_gc ELSE NULL END) AS Dilithium,\n    AVG(CASE WHEN algorithm_name = 'ECDSA' THEN num_gc ELSE NULL END) AS ECDSA,\n    AVG(CASE WHEN algorithm_name LIKE 'Falcon%' THEN num_gc ELSE NULL END) AS Falcon,\n    AVG(CASE WHEN algorithm_name LIKE 'SPHINCS+%' THEN num_gc ELSE NULL END) AS Sphincs\nFROM crypto_tests_data\nWHERE test_name = 'GenerateSignature'\nGROUP BY datetime",
     "rawQueryText": "SELECT \n    datetime,\n    AVG(CASE WHEN algorithm_name LIKE 'Dilithium%' THEN num_gc ELSE NULL END) AS Dilithium,\n    AVG(CASE WHEN algorithm_name = 'ECDSA' THEN num_gc ELSE NULL END) AS ECDSA,\n    AVG(CASE WHEN algorithm_name LIKE 'Falcon%' THEN num_gc ELSE NULL END) AS Falcon,\n    AVG(CASE WHEN algorithm_name LIKE 'SPHINCS+%' THEN num_gc ELSE NULL END) AS Sphincs\nFROM crypto_tests_data\nWHERE test_name = 'GenerateSignature'\nGROUP BY datetime"
    }
   ]
  },
  {
   "title": "📝 Signature Verification",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 5, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "SELECT \n    datetime,\n    AVG(CASE WHEN algorithm_name LIKE 'Dilithium%' THEN num_gc ELSE NULL END) AS Dilithium,\n    AVG(CASE WHEN algorithm_name = 'ECDSA' THEN num_gc ELSE NULL END) AS ECDSA,\n    AVG(CASE WHEN algorithm_name LIKE 'Falcon%' THEN num_gc ELSE NULL END) AS Falcon,\n    AVG(CASE WHEN algorithm_name LIKE 'SPHINCS+%' THEN num_gc ELSE NULL END) AS Sphincs\nFROM crypto_tests_data\nWHERE test_name = 'VerifySignature'\nGROUP BY datetime",
     "rawQueryText": "SELECT \n    datetime,\n    AVG(CASE WHEN algorithm_name LIKE 'Dilithium%' THEN num_gc ELSE NULL END) AS Dilithium,\n    AVG(CASE WHEN algorithm_name = 'ECDSA' THEN num_gc ELSE NULL END) AS ECDSA,\n    AVG(CASE WHEN algorithm_name LIKE 'Falcon%' THEN num_gc ELSE NULL END) AS Falcon,\n    AVG(CASE WHEN algorithm_name LIKE 'SPHINCS+%' THEN num_gc ELSE NULL END) AS Sphincs\nFROM crypto_tests_data\nWHERE test_name = 'VerifySignature'\nGROUP BY datetime"
    }
   ]
  }
 ]
}